version: "3.8"
services:
  rabbit:
    hostname: rabbit
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
      - RABBITMQ_HOST=rabbit
      - RABBITMQ_PORT=5672
    ports:
      - '15672:15672'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  flower:
    image: mher/flower:0.9.5
    environment:
      - CELERY_BROKER_URL=amqp://admin:mypass@rabbit:5672//
      - FLOWER_PORT=5555
      - FLOWER_PURGE_OFFLINE_WORKERS=10
    ports:
      - '5555:5555'
    links:
      - rabbit
    depends_on:
      - rabbit
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  prime_numbers:
    image: prime_numbers
    build:
      context: .
      dockerfile: ./consumer/prime_numbers_search/Dockerfile
    links:
      - rabbit
    depends_on:
      - rabbit
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure

  fastapi:
    image: producer_fastapi
    build:
      context: .
      dockerfile: ./producer/Dockerfile
    ports:
      - '8000:8000'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
